
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  password: 'password',
  avatar: 'avatar',
  emailVerified: 'emailVerified',
  image: 'image',
  activeCompanyId: 'activeCompanyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  resetOtp: 'resetOtp',
  resetOtpExpiry: 'resetOtpExpiry',
  subscriptionStatus: 'subscriptionStatus',
  subscriptionPlan: 'subscriptionPlan',
  subscriptionExpiresAt: 'subscriptionExpiresAt',
  dailyInvoiceCount: 'dailyInvoiceCount',
  dailyInvoiceResetAt: 'dailyInvoiceResetAt',
  dailyAiCount: 'dailyAiCount',
  dailyAiResetAt: 'dailyAiResetAt',
  ligdicashCustomerId: 'ligdicashCustomerId'
};

exports.Prisma.PaymentTransactionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  ligdicashRef: 'ligdicashRef',
  plan: 'plan',
  amountUsd: 'amountUsd',
  amountLocal: 'amountLocal',
  currency: 'currency',
  status: 'status',
  processedAt: 'processedAt',
  createdAt: 'createdAt'
};

exports.Prisma.CompanyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  legalName: 'legalName',
  taxId: 'taxId',
  address: 'address',
  email: 'email',
  phone: 'phone',
  logoUrl: 'logoUrl',
  website: 'website',
  leaderName: 'leaderName',
  legalForm: 'legalForm',
  registrationNumber: 'registrationNumber',
  sector: 'sector',
  description: 'description',
  productsServices: 'productsServices',
  targetMarket: 'targetMarket',
  annualRevenue: 'annualRevenue',
  monthlyRevenue: 'monthlyRevenue',
  employeeCount: 'employeeCount',
  departments: 'departments',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ClientScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  phone: 'phone',
  address: 'address',
  poBox: 'poBox',
  contact: 'contact',
  firstName: 'firstName',
  age: 'age',
  sexe: 'sexe',
  city: 'city',
  country: 'country',
  companyName: 'companyName',
  jobTitle: 'jobTitle',
  type: 'type',
  status: 'status',
  preferredPaymentMethod: 'preferredPaymentMethod',
  notes: 'notes',
  zipCode: 'zipCode',
  taxId: 'taxId',
  totalSpent: 'totalSpent',
  paidInvoicesCount: 'paidInvoicesCount',
  unpaidInvoicesCount: 'unpaidInvoicesCount',
  userId: 'userId',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  price: 'price',
  taxRate: 'taxRate',
  unit: 'unit',
  type: 'type',
  companyId: 'companyId',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ExpenseScalarFieldEnum = {
  id: 'id',
  title: 'title',
  amount: 'amount',
  date: 'date',
  category: 'category',
  description: 'description',
  userId: 'userId',
  companyId: 'companyId',
  isDeductible: 'isDeductible',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TodoScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  completed: 'completed',
  status: 'status',
  priority: 'priority',
  category: 'category',
  startTime: 'startTime',
  endTime: 'endTime',
  reminderAt: 'reminderAt',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvoiceScalarFieldEnum = {
  id: 'id',
  reference: 'reference',
  invoiceNumber: 'invoiceNumber',
  type: 'type',
  status: 'status',
  city: 'city',
  clientName: 'clientName',
  object: 'object',
  clientAddress: 'clientAddress',
  clientContact: 'clientContact',
  clientPOBox: 'clientPOBox',
  managerName: 'managerName',
  companyName: 'companyName',
  clientId: 'clientId',
  companyId: 'companyId',
  totalHT: 'totalHT',
  totalMaterial: 'totalMaterial',
  amountWords: 'amountWords',
  description: 'description',
  taxAmount: 'taxAmount',
  totalTTC: 'totalTTC',
  pdfUrl: 'pdfUrl',
  pdfPublicId: 'pdfPublicId',
  userId: 'userId',
  isRecurring: 'isRecurring',
  recurrenceFreq: 'recurrenceFreq',
  nextIssueDate: 'nextIssueDate',
  dueDate: 'dueDate',
  paidAmount: 'paidAmount',
  paymentMethod: 'paymentMethod',
  paidAt: 'paidAt',
  reminderTone: 'reminderTone',
  autoReminders: 'autoReminders',
  lastReminderSentAt: 'lastReminderSentAt',
  remindersSentCount: 'remindersSentCount',
  nextReminderDate: 'nextReminderDate',
  isScaled: 'isScaled',
  isRead: 'isRead',
  readAt: 'readAt',
  style: 'style',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvoiceItemScalarFieldEnum = {
  id: 'id',
  designation: 'designation',
  unit: 'unit',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  totalPrice: 'totalPrice',
  productId: 'productId',
  invoiceId: 'invoiceId'
};

exports.Prisma.PushSubscriptionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  endpoint: 'endpoint',
  p256dh: 'p256dh',
  auth: 'auth',
  createdAt: 'createdAt'
};

exports.Prisma.FeedbackScalarFieldEnum = {
  id: 'id',
  content: 'content',
  rating: 'rating',
  userId: 'userId',
  createdAt: 'createdAt'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires'
};

exports.Prisma.VerificationTokenScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  token: 'token',
  expires: 'expires'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};


exports.Prisma.ModelName = {
  User: 'User',
  PaymentTransaction: 'PaymentTransaction',
  Company: 'Company',
  Client: 'Client',
  Product: 'Product',
  Expense: 'Expense',
  Todo: 'Todo',
  Invoice: 'Invoice',
  InvoiceItem: 'InvoiceItem',
  PushSubscription: 'PushSubscription',
  Feedback: 'Feedback',
  Account: 'Account',
  Session: 'Session',
  VerificationToken: 'VerificationToken'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
